// <auto-generated />
using System;
using HumanParts.Detection.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HumanParts.Detection.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190328174610_01_nlpsql")]
    partial class _01_nlpsql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HumanParts.Detection.API.Models.DetectedObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("DetectedObjects");
                });

            modelBuilder.Entity("HumanParts.Detection.API.Models.DetectionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("detectedObjectId");

                    b.Property<DateTime>("detectionTime");

                    b.Property<int>("deviceId");

                    b.HasKey("Id");

                    b.HasIndex("detectedObjectId");

                    b.HasIndex("deviceId");

                    b.ToTable("Detections");
                });

            modelBuilder.Entity("HumanParts.Detection.API.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("OperatingSystemVersion");

                    b.Property<string>("rosVersion");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("HumanParts.Detection.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HumanParts.Detection.API.Models.DetectionModel", b =>
                {
                    b.HasOne("HumanParts.Detection.API.Models.DetectedObject", "detectedObject")
                        .WithMany()
                        .HasForeignKey("detectedObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HumanParts.Detection.API.Models.Device", "device")
                        .WithMany()
                        .HasForeignKey("deviceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
